version: "3"
services:
  app-poc:
    image: app-poc
    ports:
      - "8080:8080"
    networks:
      - app-mysql_network
    depends_on:
      - mysqlhost
 
  mysqlhost:
    image: mysql:5.7
    networks:
      - app-mysql_network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=task_management 

networks:
  app-mysql_network: 